### ISSUE TITLE
Unable to create Corridor environments

### ISSUE THREAD

**Issue by alaflaquiere** [MiniHackPlanet/MiniHack#4]
Trying to create any of the Corridor environments (Corridor-R2-v0, Corridor-R3-v0, Corridor-R5-v0) leads to a " ModuleNotFoundError: No module named 'minihack' " error.

--- Code ---
```
import gym
import nle
env = gym.make(""MiniHack-Corridor-R2-v0"")
```

--- Complete error message ---
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-16-738b24d0e911> in <module>
----> 1 env = gym.make("MiniHack-Corridor-R2-v0")

/usr/local/lib/python3.8/dist-packages/gym/envs/registration.py in make(id, **kwargs)
    143 
    144 def make(id, **kwargs):
--> 145     return registry.make(id, **kwargs)
    146 
    147 def spec(id):

/usr/local/lib/python3.8/dist-packages/gym/envs/registration.py in make(self, path, **kwargs)
     88             logger.info('Making new env: %s', path)
     89         spec = self.spec(path)
---> 90         env = spec.make(**kwargs)
     91         # We used to have people override _reset/_step rather than
     92         # reset/step. Set _gym_disable_underscore_compat = True on

/usr/local/lib/python3.8/dist-packages/gym/envs/registration.py in make(self, **kwargs)
     57             env = self.entry_point(**_kwargs)
     58         else:
---> 59             cls = load(self.entry_point)
     60             env = cls(**_kwargs)
     61 

/usr/local/lib/python3.8/dist-packages/gym/envs/registration.py in load(name)
     16 def load(name):
     17     mod_name, attr_name = name.split(":")
---> 18     mod = importlib.import_module(mod_name)
     19     fn = getattr(mod, attr_name)
     20     return fn

/usr/lib/python3.8/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

/usr/lib/python3.8/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.8/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.8/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.8/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/usr/lib/python3.8/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.8/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.8/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/usr/lib/python3.8/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

/usr/lib/python3.8/importlib/_bootstrap.py in _gcd_import(name, package, level)

/usr/lib/python3.8/importlib/_bootstrap.py in _find_and_load(name, import_)

/usr/lib/python3.8/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'minihack'

**Comment by MiniHackPlanet** [comment]
This should be fixed now with https://github.com/MiniHackPlanet/MiniHack/commit/4288f6899ecc3103709a5121d317ffb1224cf1a5. Please reopen if there is still a problem. Thank you.
