### ISSUE TITLE
[FEATURE] Get a list of all possible objects in environment

### ISSUE THREAD

**Issue by Spiph** [MiniHackPlanet/MiniHack#4]
## 🚀 Feature

I would like to have an indexable list of objects that exist in the current environment. This would potentially be different between different tasks and skills where some tasks may have lava, monsters, etc. while others simply have floors, walls, and stairs.

## Motivation

Doing this would allow agents to have right-sized observation indexes vs having to index the entire glyph space, where many of the objects would not be used in the environment.

## Alternatives

Does there already exist a way to be doing this? If so, please describe what is required to do this.

**Comment by samvelyan** [comment]
Hi @Spiph . Thanks for your interest in MiniHack.

We have moved the repository to [facebookresearch/minihack](https://github.com/facebookresearch/minihack). Could you please copy your issue there? This repository will soon be archived.

Thanks!
